### ISSUE TITLE
Build failed on io.js v2.3.1

### ISSUE THREAD

**Issue by llevkin** [kuno/GeoIP#81]
npm i geoip
\
> geoip@0.5.7 install /node/node_modules/geoip
> node-gyp rebuild

make: Entering directory `/node/node_modules/geoip/build'
  CC(target) Release/obj.target/libgeoip/deps/GeoIP-1.6.2/libGeoIP/GeoIP.o
../deps/GeoIP-1.6.2/libGeoIP/GeoIP.c: In function ‘_get_name_gl’:
../deps/GeoIP-1.6.2/libGeoIP/GeoIP.c:2256:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
../deps/GeoIP-1.6.2/libGeoIP/GeoIP.c: In function ‘_get_name_v6_gl’:
../deps/GeoIP-1.6.2/libGeoIP/GeoIP.c:2315:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
../deps/GeoIP-1.6.2/libGeoIP/GeoIP.c: In function ‘GeoIP_range_by_ip_gl’:
../deps/GeoIP-1.6.2/libGeoIP/GeoIP.c:2399:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
../deps/GeoIP-1.6.2/libGeoIP/GeoIP.c:2408:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  CC(target) Release/obj.target/libgeoip/deps/GeoIP-1.6.2/libGeoIP/GeoIPCity.o
  CC(target) Release/obj.target/libgeoip/deps/GeoIP-1.6.2/libGeoIP/timeZone.o
  CC(target) Release/obj.target/libgeoip/deps/GeoIP-1.6.2/libGeoIP/regionName.o
  CC(target) Release/obj.target/libgeoip/deps/GeoIP-1.6.2/libGeoIP/GeoIP_deprecated.o
  AR(target) Release/obj.target/deps/GeoIP-1.6.2/libgeoip.a
  COPY Release/libgeoip.a
  CXX(target) Release/obj.target/native/src/global.o
In file included from ../src/global.h:10:0,
                 from ../src/global.cc:7:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Signature> NanNew(v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../node_modules/nan/nan.h:207:78: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)’
../node_modules/nan/nan.h:207:78: note: candidate is:
In file included from ../src/global.h:9:0,
                 from ../src/global.cc:7:
/home/app/.node-gyp/2.3.1/deps/v8/include/v8.h:4188:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
/home/app/.node-gyp/2.3.1/deps/v8/include/v8.h:4188:27: note:   candidate expects 2 arguments, 4 provided
make: *** [Release/obj.target/native/src/global.o] Error 1
make: Leaving directory `/node/node_modules/geoip/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node/node_modules/geoip
gyp ERR! node -v v2.3.1
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "i" "geoip"
npm ERR! node v2.3.1
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! geoip@0.5.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the geoip@0.5.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the geoip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls geoip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /node/npm-debug.log

**Comment by kuno** [comment]
Fixed in new version.

Done
